name: Deploy

on:
  push:
    branches: [ development, github-action-gpg-fix ] # FIXME remove test branch name


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven local repository
        uses: actions/cache@v2.1.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # This is a temporary workaround until stable PacketWrapper Legacy support is not merged into upstream
      - name: Build submodules
        run: ./build-submodules.sh

      - name: Import GPG signing key
        run: |
          echo -e "${{ secrets.CODE_SIGNING_GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      # TODO check version
      - name: Deploy snapshot
        env:
          CODE_SIGNING_GPG_KEY_ID: ${{ secrets.CODE_SIGNING_GPG_KEY_ID }}
          CODE_SIGNING_GPG_PASSPHRASE: ${{ secrets.CODE_SIGNING_GPG_PASSPHRASE }}
        run: ./.github-actions/scripts/maven_deploy.sh
